:toc:
:icons: font
:source-highlighter: prettify
:project_id: tut-spring-boot-kotlin
:images: https://raw.githubusercontent.com/spring-guides/tut-spring-boot-kotlin/master/images
:tabsize: 2

Este tutorial mostra como criar eficientemente uma aplicação de um blog de exemplo combinando o poder de  https://spring.io/projects/spring-boot/[Spring Boot] and https://kotlinlang.org/[Kotlin].

Se você está começando com Kotlin, você pode aprender a linguagem lendo a https://kotlinlang.org/docs/reference/[documentação de referência], seguindo o online https://play.kotlinlang.org/[Tutorial de Kotlin Koans] ou apenas usando a https://docs.spring.io/spring/docs/current/spring-framework-reference/[documentação de referência do Spring Framework] que agora fornece exemplos de código no Kotlin.

O suporte ao Spring Kotlin está documentado na documentação de referência do https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin[Spring Framework] e https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-kotlin.html[Spring Boot] reference documentation. Se precisar de ajuda, pesquise ou tire suas dúvidas com o https://stackoverflow.com/questions/tagged/kotlin+spring[`spring` e `kotlin` tags no StackOverflow] ou venha discutir no canal do https://slack.kotlinlang.org/[Kotlin Slack] `#spring`.

== Criando um novo projeto

Primeiro precisamos criar uma aplicação `Spring Boot`, o que pode ser feito de várias maneiras.

[[usando-o-site-initializr]]
=== Usando o site Initializr

Visite https://start.spring.io e escolha a linguagem `Kotlin`.
Gradle é a ferramenta de compilação mais comumente usada no Kotlin, e fornece uma DSL Kotlin que é usada por padrão ao gerar um projeto Kotlin, então esta é a escolha recomendada. Mas você também pode usar o Maven se estiver mais confortável com ele
Observe que você pode usar https://start.spring.io/#!language=kotlin&type=gradle-project-kotlin para ter Kotlin e Gradle selecionados por padrão

	. Selecione "Gradle - Kotlin" ou "Maven" dependendo de qual ferramenta de compilação você deseja usar
	. Insira as seguinte artefato: `blog`
	. Adicione as seguintes dependências:
		- Spring Web
		- Mustache
		- Spring Data JPA
		- H2 Database
		- Spring Boot DevTools
	. Clique em "Generate Project".

O arquivo .zip contém um projeto padrão no diretório raiz, portanto, convém criar um diretório vazio antes de descompactá-lo.

[[usando-linha-de-comando]]
=== Usando linha de comando

Você pode usar a API HTTP `Initializr` https://docs.spring.io/initializr/docs/current/reference/html/#command-line[por linha de comando], por exemplo, `curl` em sistemas baseados em UNIX like system:

[source]
----
$ mkdir blog && cd blog
$ curl https://start.spring.io/starter.zip -d language=kotlin -d type=gradle-project-kotlin -d dependencies=web,mustache,jpa,h2,devtools -d packageName=com.example.blog -d name=Blog -o blog.zip
----

Adicione `-d type=gradle-project` Se vocë quiser usar `Gradle`.

[[usando-intellij-idea]]
=== Usando IntelliJ IDEA

O `Spring Initializr` também esta integrado no IntelliJ IDEA Ultimate edition e e permite que você `crie` e `import` um novo projeto sem ter que sair da IDE para a linha de comando ou a interface do usuário da Web.

Para acessar o wizard, para o o menu File | New | Project, e selecione `Spring Initializr`.

Siga as etapas do assistente para usar os seguintes parâmetros::

 - Artifact: "blog"
 - Type: "Gradle - Kotlin" or "Maven"
 - Language: Kotlin
 - Name: "Blog"
 - Dependências: "Spring Web Starter", "Mustache", "Spring Data JPA", "H2 Database" and "Spring Boot DevTools"

[[gradle-build]]
== Entendendo o Gradle Build

If you're using a Maven Build, you can <<maven-build, skip to the dedicated section>>.
Se você estiver usando o Maven, poderá pular para a seção dedicada.

=== Plugins

Além do óbvio https://kotlinlang.org/docs/gradle.html[Kotlin Gradle plugin], a configuração padrão declara https://kotlinlang.org/docs/all-open-plugin.html#spring-support[kotlin-spring plugin] que abre automaticamente classes e métodos (ao contrário do Java, o qualificador padrão no Kotlin é `final`) anotados ou meta-anotados com anotações Spring. Isso é útil para poder criar beans `@Configuration` ou `@Transactional` sem ter que adicionar o qualificador `open` por exemplo, exigido por proxies CGLIB.
Para poder usar as propriedades não non-nullable do Kotlin com JPA, o https://kotlinlang.org/docs/reference/compiler-plugins.html#jpa-support[Kotlin JPA plugin] também está ativado. Ele gera construtores `no-arg` para qualquer classe anotada com `@Entity`, `@MappedSuperclass` or `@Embeddable`.

`build.gradle.kts`
[source,kotlin]
----
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "3.0.1"
	id("io.spring.dependency-management") version "1.1.0"
	kotlin("jvm") version "1.8.0"
	kotlin("plugin.spring") version "1.8.0"
	kotlin("plugin.jpa") version "1.8.0"
}
----

=== Opções do compilador

Uma das principais características de Kotlin é https://kotlinlang.org/docs/null-safety.html[null-safety] - 
Que lida de forma limpa com o valores `null` em tempo de compilação em vez de esbarrar no famoso `null` `NullPointerException` em tempo de execução. 
Isso torna as aplicações mais seguras por meio de declarações nullability e expressando "value or no value" semântica sem pagar o custo de usar `Optional`. 
Observe que Kotlin permite o uso de construções funcionais com valores anuláveis; veja https://www.baeldung.com/kotlin/null-safety[comprehensive guide to Kotlin null-safety].

Embora o Java não permita que alguém expresse `null-safety` em seu `type-system`, Spring Framework fornece `null-safety` de toda API Spring Framework por meio de anotações `tooling-friendly` declarada no pacote `org.springframework.lang`. 
Por padrão, tipos de APIs Java usado em Kotlin são reconhecidos como https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[platform types] para os quais `null-checks` são relaxados. https://kotlinlang.org/docs/java-interop.html#jsr-305-support[Kotlin support for JSR 305 annotations] + anotações Spring nullability fornece `null-safety` por toda API Spring Framework para desenvolvedores Kotlin, com a vantagem de lidar com problemas relacionados com `null` em tempo de compilação.

Este recurso pode ser habilitado adicionando a flag de compilação `-Xjsr305` com a opção `strict`.

`build.gradle.kts`
[source,kotlin]
----
tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xjsr305=strict"
	}
}
----

=== Dependências

2 bibliotecas específicas do Kotlin são necessárias (a biblioteca padrão é adicionada automaticamente com o Gradle) para essa aplicação Web Spring Boot e configuradas por padrão:

 - `kotlin-reflect` é a biblioteca de `reflection` do kotlin
 - `jackson-module-kotlin` adiciona suporte para serialization/deserialization de classes Kotlin e data classes (classes de construtor único podem ser usadas automaticamente, e aquelas com construtores secundários ou static factories também são suportadas)

`build.gradle.kts`
[source,kotlin]
----
dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-mustache")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	runtimeOnly("com.h2database:h2")
	runtimeOnly("org.springframework.boot:spring-boot-devtools")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}
----

Recente versões de `H2` exigem configurações especiais adequadamente de keywords reservadas `user`.

`src/main/resources/application.properties`
[source,properties]
----
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true
----

O plugin Spring Boot Gradle usa automaticamente a versão Kotlin declarada através do plugin Kotlin Gradle.

Você pode ver <<understanding-generated-app, deeper look at the generated application>>.

[[maven-build]]
== Entendendo o Maven Build

=== Plugins

Além do óbvio https://kotlinlang.org/docs/reference/using-maven.html[Kotlin Maven plugin], a configuração padrão declara o https://kotlinlang.org/docs/reference/compiler-plugins.html#spring-support[kotlin-spring plugin] que automaticamente classes e métodos são `opens` (ao contrário do Java, o qualificador padrão do kotlin é `final`) anotado ou meta-annotated com Spring annotations. 
Isto é útil para habilitar a criação de beas `@Configuration` or `@Transactional` sem ter que adicionar o qualificador `open` exigido por exemplo por CGLIB proxies.

Para poder usar a propriedade do Kotlin non-nullable com JPA, https://kotlinlang.org/docs/reference/compiler-plugins.html#jpa-support[Kotlin JPA plugin] também está habilitado. 
Gera construtores `no-arg` para qualquer classe anotada com `@Entity`, `@MappedSuperclass` or `@Embeddable`.

`pom.xml`
[source,xml]
----
<build>
		<sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-plugin</artifactId>
				<configuration>
					<compilerPlugins>
						<plugin>jpa</plugin>
						<plugin>spring</plugin>
					</compilerPlugins>
					<args>
						<arg>-Xjsr305=strict</arg>
					</args>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.jetbrains.kotlin</groupId>
						<artifactId>kotlin-maven-noarg</artifactId>
						<version>${kotlin.version}</version>
					</dependency>
					<dependency>
						<groupId>org.jetbrains.kotlin</groupId>
						<artifactId>kotlin-maven-allopen</artifactId>
						<version>${kotlin.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
----

Uma das principais características de Kotlin é https://kotlinlang.org/docs/null-safety.html[null-safety] - que lida de forma limpa com valores `null` em tempo de compilação em vez de esbarrar no famoso `NullPointerException` em tempo de execução. 
Isso torna os aplicativos mais seguros por meio de declarações de `nullability` e expressões "value or no value" semântica sem pagar o custo de usar `Optional`. 
Observe que Kotlin permite o uso de construções funcionais com valores anuláveis; veja https://www.baeldung.com/kotlin/null-safety[comprehensive guide to Kotlin null-safety].

Embora o Java não permita `null-safety` em seu `type-system`, Spring Framework fornece `null-safety` em toda toda sua API Spring Framework por meio de anotações `tooling-friendly` declaradas no pacote `org.springframework.lang`. 
Por padrão, tipos de APIs Java usado em Kotlin são reconhecidos como https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[platform types] onde `null-checks` são relaxados. https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support[Kotlin support for JSR 305 annotations] + anotação Spring nullability fornece `null-safety` por toda API Spring Framework para desenvolvedores Kotlin, com a vantagem de lidar com problemas relacionados com `null` em tempo de compilação.

Este recurso pode ser habilitado adicionando a flag de compilação `-Xjsr305` com a opção `strict`.

Observe também que o compilador Kotlin está configurado para gerar código de bytes Java 8 (Java 6 por padrão).

=== Dependências

3 Kotlin specific libraries are required for such Spring Boot web application and configured by default:

 - `kotlin-stdlib` is the Kotlin standard library
 - `kotlin-reflect` is Kotlin reflection library
 - `jackson-module-kotlin` adiocional suporte de serialization/deserialization de Kotlin class and data classes (classes de construtor único podem ser usadas automaticamente, e aquelas com construtores secundários ou `static factories` também são suportadas)

`pom.xml`
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-mustache</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
	<dependency>
		<groupId>com.fasterxml.jackson.module</groupId>
		<artifactId>jackson-module-kotlin</artifactId>
	</dependency>
	<dependency>
		<groupId>org.jetbrains.kotlin</groupId>
		<artifactId>kotlin-reflect</artifactId>
	</dependency>
	<dependency>
		<groupId>org.jetbrains.kotlin</groupId>
		<artifactId>kotlin-stdlib</artifactId>
	</dependency>

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-devtools</artifactId>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>com.h2database</groupId>
		<artifactId>h2</artifactId>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
	</dependency>
</dependencies>
----

[[understanding-generated-app]]
== Entendendo a aplicação gerada

`src/main/kotlin/com/example/blog/BlogApplication.kt`
[source,kotlin]
----
package com.example.blog

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class BlogApplication

fun main(args: Array<String>) {
	runApplication<BlogApplication>(*args)
}
----

Compared to Java, you can notice the lack of semicolons, the lack of brackets on empty class (you can add some if you need to declare beans via `@Bean` annotation) and the use of `runApplication` top level function. `runApplication<BlogApplication>(*args)` is Kotlin idiomatic alternative to `SpringApplication.run(BlogApplication::class.java, *args)` and can be used to customize the application with following syntax.

`src/main/kotlin/com/example/blog/BlogApplication.kt`
[source,kotlin]
----
fun main(args: Array<String>) {
	runApplication<BlogApplication>(*args) {
		setBannerMode(Banner.Mode.OFF)
	}
}
----

== Escrevendo sua primeiro controller Kotlin

Let's create a simple controller to display a simple web page.

`src/main/kotlin/com/example/blog/HtmlController.kt`
[source,kotlin]
----
package com.example.blog

import org.springframework.stereotype.Controller
import org.springframework.ui.Model
import org.springframework.ui.set
import org.springframework.web.bind.annotation.GetMapping

@Controller
class HtmlController {

	@GetMapping("/")
	fun blog(model: Model): String {
		model["title"] = "Blog"
		return "blog"
	}

}
----

Notice that we are using here a https://kotlinlang.org/docs/extensions.html[Kotlin extension] that allows to add Kotlin functions or operators to existing Spring types. Here we import the `org.springframework.ui.set` extension function in order to be able to write `model["title"] = "Blog"` instead of `model.addAttribute("title", "Blog")`.
The https://docs.spring.io/spring-framework/docs/current/kdoc-api/[Spring Framework KDoc API] lists all the Kotlin extensions provided to enrich the Java API.

We also need to create the associated Mustache templates.

`src/main/resources/templates/header.mustache`
[source]
----
<html>
<head>
	<title>{{title}}</title>
</head>
<body>
----

`src/main/resources/templates/footer.mustache`
[source]
----
</body>
</html>
----

`src/main/resources/templates/blog.mustache`
[source]
----
{{> header}}

<h1>{{title}}</h1>

{{> footer}}
----

Start the web application by running the `main` function of `BlogApplication.kt`, and go to `http://localhost:8080/`, you should see a sober web page with a "Blog" headline. 

== Testando com JUnit 5

JUnit 5 now used by default in Spring Boot provides various features very handy with Kotlin, including https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testcontext-junit-jupiter-di[autowiring of constructor/method parameters] which allows to use non-nullable `val` properties and the possibility to use `@BeforeAll`/`@AfterAll` on regular non-static methods.

=== Escrevendo teste in Kotlin com JUnit 5

For the sake of this example, let's create an integration test in order to demonstrate various features:

 - We use real sentences between backticks instead of camel-case to provide expressive test function names
 - JUnit 5 allows to inject constructor and method parameters, which is a good fit with Kotlin read-only and non-nullable properties
 - This code leverages `getForObject` and `getForEntity` Kotlin extensions (you need to import them)

`src/test/kotlin/com/example/blog/IntegrationTests.kt`
[source,kotlin]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class IntegrationTests(@Autowired val restTemplate: TestRestTemplate) {

	@Test
	fun `Assert blog page title, content and status code`() {
		val entity = restTemplate.getForEntity<String>("/")
		assertThat(entity.statusCode).isEqualTo(HttpStatus.OK)
		assertThat(entity.body).contains("<h1>Blog</h1>")
	}

}
----

=== Ciclo de vida da instância de teste

Sometimes you need to execute a method before or after all tests of a given class. Like Junit 4, JUnit 5 requires by default these methods to be static (which translates to https://kotlinlang.org/docs/object-declarations.html#companion-objects[`companion object`] in Kotlin, which is quite verbose and not straightforward) because test classes are instantiated one time per test.

But Junit 5 allows you to change this default behavior and instantiate test classes one time per class. This can be done in https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle[various ways], here we will use a property file to change the default behavior for the whole project:

`src/test/resources/junit-platform.properties`
[source,properties]
----
junit.jupiter.testinstance.lifecycle.default = per_class
----

With this configuration, we can now use `@BeforeAll` and `@AfterAll` annotations on regular methods like shown in updated version of `IntegrationTests` above.

`src/test/kotlin/com/example/blog/IntegrationTests.kt`
[source,kotlin]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class IntegrationTests(@Autowired val restTemplate: TestRestTemplate) {

	@BeforeAll
	fun setup() {
		println(">> Setup")
	}

	@Test
	fun `Assert blog page title, content and status code`() {
		println(">> Assert blog page title, content and status code")
		val entity = restTemplate.getForEntity<String>("/")
		assertThat(entity.statusCode).isEqualTo(HttpStatus.OK)
		assertThat(entity.body).contains("<h1>Blog</h1>")
	}

	@Test
	fun `Assert article page title, content and status code`() {
		println(">> TODO")
	}

	@AfterAll
	fun teardown() {
		println(">> Tear down")
	}

}
----

== Criando suas próprias extensions

Instead of using util classes with abstract methods like in Java, it is usual in Kotlin to provide such functionalities via Kotlin extensions. Here we are going to add a `format()` function to the existing `LocalDateTime` type in order to generate text with the English date format.

`src/main/kotlin/com/example/blog/Extensions.kt`
[source,kotlin]
----
fun LocalDateTime.format(): String = this.format(englishDateFormatter)

private val daysLookup = (1..31).associate { it.toLong() to getOrdinal(it) }

private val englishDateFormatter = DateTimeFormatterBuilder()
		.appendPattern("yyyy-MM-dd")
		.appendLiteral(" ")
		.appendText(ChronoField.DAY_OF_MONTH, daysLookup)
		.appendLiteral(" ")
		.appendPattern("yyyy")
		.toFormatter(Locale.ENGLISH)

private fun getOrdinal(n: Int) = when {
	n in 11..13 -> "${n}th"
	n % 10 == 1 -> "${n}st"
	n % 10 == 2 -> "${n}nd"
	n % 10 == 3 -> "${n}rd"
	else -> "${n}th"
}

fun String.toSlug() = lowercase(Locale.getDefault())
		.replace("\n", " ")
		.replace("[^a-z\\d\\s]".toRegex(), " ")
		.split(" ")
		.joinToString("-")
		.replace("-+".toRegex(), "-")
----

We will leverage these extensions in the next section.

== Persistencia de dados com JPA

In order to make lazy fetching working as expected, entities should be `open` as described in https://youtrack.jetbrains.com/issue/KT-28525[KT-28525]. We are going to use the Kotlin `allopen` plugin for that purpose.

With Gradle:

`build.gradle.kts`
[source,kotlin]
----
plugins {
	...
	kotlin("plugin.allopen") version "1.8.0"
}

allOpen {
	annotation("jakarta.persistence.Entity")
	annotation("jakarta.persistence.Embeddable")
	annotation("jakarta.persistence.MappedSuperclass")
}
----

Or with Maven:

`pom.xml`
[source,xml]
----
<plugin>
	<artifactId>kotlin-maven-plugin</artifactId>
	<groupId>org.jetbrains.kotlin</groupId>
	<configuration>
		...
		<compilerPlugins>
			...
			<plugin>all-open</plugin>
		</compilerPlugins>
		<pluginOptions>
			<option>all-open:annotation=jakarta.persistence.Entity</option>
			<option>all-open:annotation=jakarta.persistence.Embeddable</option>
			<option>all-open:annotation=jakarta.persistence.MappedSuperclass</option>
		</pluginOptions>
	</configuration>
</plugin>
----

Then we create our model by using Kotlin https://kotlinlang.org/docs/reference/classes.html#constructors[primary constructor concise syntax] which allows to declare at the same time the properties and the constructor parameters.

`src/main/kotlin/com/example/blog/Entities.kt`
[source,kotlin]
----
@Entity
class Article(
		var title: String,
		var headline: String,
		var content: String,
		@ManyToOne var author: User,
		var slug: String = title.toSlug(),
		var addedAt: LocalDateTime = LocalDateTime.now(),
		@Id @GeneratedValue var id: Long? = null)

@Entity
class User(
		var login: String,
		var firstname: String,
		var lastname: String,
		var description: String? = null,
		@Id @GeneratedValue var id: Long? = null)
----

Notice that we are using here our `String.toSlug()` extension to provide a default argument to the `slug` parameter of `Article` constructor. Optional parameters with default values are defined at the last position in order to make it possible to omit them when using positional arguments (Kotlin also supports https://kotlinlang.org/docs/reference/functions.html#named-arguments[named arguments]). Notice that in Kotlin it is not unusual to group concise class declarations in the same file.

NOTE: Here we don't use https://kotlinlang.org/docs/data-classes.html[`data` classes] with `val` properties because JPA is not designed to work with immutable classes or the methods generated automatically by `data` classes. If you are using other Spring Data flavor, most of them are designed to support such constructs so you should use classes like `data class User(val login: String, ...)` when using Spring Data MongoDB, Spring Data JDBC, etc.

NOTE: While Spring Data JPA makes it possible to use natural IDs (it could have been the `login` property in `User` class) via https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.entity-persistence.saving-entites[`Persistable`], it is not a good fit with Kotlin due to https://youtrack.jetbrains.com/issue/KT-6653[KT-6653], that's why it is recommended to always use entities with generated IDs in Kotlin.


We also declare our Spring Data JPA repositories as following.

`src/main/kotlin/com/example/blog/Repositories.kt`
[source,kotlin]
----
interface ArticleRepository : CrudRepository<Article, Long> {
	fun findBySlug(slug: String): Article?
	fun findAllByOrderByAddedAtDesc(): Iterable<Article>
}

interface UserRepository : CrudRepository<User, Long> {
	fun findByLogin(login: String): User?
}
----

And we write JPA tests to check whether basic use cases work as expected.

`src/test/kotlin/com/example/blog/RepositoriesTests.kt`
[source,kotlin]
----
@DataJpaTest
class RepositoriesTests @Autowired constructor(
		val entityManager: TestEntityManager,
		val userRepository: UserRepository,
		val articleRepository: ArticleRepository) {

	@Test
	fun `When findByIdOrNull then return Article`() {
		val johnDoe = User("johnDoe", "John", "Doe")
		entityManager.persist(johnDoe)
		val article = Article("Lorem", "Lorem", "dolor sit amet", johnDoe)
		entityManager.persist(article)
		entityManager.flush()
		val found = articleRepository.findByIdOrNull(article.id!!)
		assertThat(found).isEqualTo(article)
	}

	@Test
	fun `When findByLogin then return User`() {
		val johnDoe = User("johnDoe", "John", "Doe")
		entityManager.persist(johnDoe)
		entityManager.flush()
		val user = userRepository.findByLogin(johnDoe.login)
		assertThat(user).isEqualTo(johnDoe)
	}
}
----

NOTE: We use here the `CrudRepository.findByIdOrNull` Kotlin extension provided by default with Spring Data, which is a nullable variant of the `Optional` based `CrudRepository.findById`. Read the great https://medium.com/@elizarov/null-is-your-friend-not-a-mistake-b63ff1751dd5[Null is your friend, not a mistake] blog post for more details.

== Implementando o mecanismo de blog

We update the "blog" Mustache templates.

`src/main/resources/templates/blog.mustache`
[source]
----
{{> header}}

<h1>{{title}}</h1>

<div class="articles">

	{{#articles}}
		<section>
			<header class="article-header">
				<h2 class="article-title"><a href="/article/{{slug}}">{{title}}</a></h2>
				<div class="article-meta">By  <strong>{{author.firstname}}</strong>, on <strong>{{addedAt}}</strong></div>
			</header>
			<div class="article-description">
				{{headline}}
			</div>
		</section>
	{{/articles}}
</div>

{{> footer}}
----

And we create an "article" new one.

`src/main/resources/templates/article.mustache`
[source]
----
{{> header}}

<section class="article">
	<header class="article-header">
		<h1 class="article-title">{{article.title}}</h1>
		<p class="article-meta">By  <strong>{{article.author.firstname}}</strong>, on <strong>{{article.addedAt}}</strong></p>
	</header>

	<div class="article-description">
		{{article.headline}}

		{{article.content}}
	</div>
</section>

{{> footer}}
----

We update the `HtmlController` in order to render blog and article pages with the formatted date. `ArticleRepository` and `MarkdownConverter` constructor parameters will be automatically autowired since `HtmlController` has a single constructor (implicit `@Autowired`).

`src/main/kotlin/com/example/blog/HtmlController.kt`
[source,kotlin]
----
@Controller
class HtmlController(private val repository: ArticleRepository) {

	@GetMapping("/")
	fun blog(model: Model): String {
		model["title"] = "Blog"
		model["articles"] = repository.findAllByOrderByAddedAtDesc().map { it.render() }
		return "blog"
	}

	@GetMapping("/article/{slug}")
	fun article(@PathVariable slug: String, model: Model): String {
		val article = repository
				.findBySlug(slug)
				?.render()
				?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "This article does not exist")
		model["title"] = article.title
		model["article"] = article
		return "article"
	}

	fun Article.render() = RenderedArticle(
			slug,
			title,
			headline,
			content,
			author,
			addedAt.format()
	)

	data class RenderedArticle(
			val slug: String,
			val title: String,
			val headline: String,
			val content: String,
			val author: User,
			val addedAt: String)

}
----

Then, we add data initialization to a new `BlogConfiguration` class.

`src/main/kotlin/com/example/blog/BlogConfiguration.kt`
[source,kotlin]
----
@Configuration
class BlogConfiguration {

	@Bean
	fun databaseInitializer(userRepository: UserRepository,
							articleRepository: ArticleRepository) = ApplicationRunner {

		val johnDoe = userRepository.save(User("johnDoe", "John", "Doe"))
		articleRepository.save(Article(
				title = "Lorem",
				headline = "Lorem",
				content = "dolor sit amet",
				author = johnDoe
		))
		articleRepository.save(Article(
				title = "Ipsum",
				headline = "Ipsum",
				content = "dolor sit amet",
				author = johnDoe
		))
	}
}
----

NOTE: Notice the usage of named parameters to make the code more readable.

And we also update the integration tests accordingly.

`src/test/kotlin/com/example/blog/IntegrationTests.kt`
[source,kotlin]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class IntegrationTests(@Autowired val restTemplate: TestRestTemplate) {

	@BeforeAll
	fun setup() {
		println(">> Setup")
	}

	@Test
	fun `Assert blog page title, content and status code`() {
		println(">> Assert blog page title, content and status code")
		val entity = restTemplate.getForEntity<String>("/")
		assertThat(entity.statusCode).isEqualTo(HttpStatus.OK)
		assertThat(entity.body).contains("<h1>Blog</h1>", "Lorem")
	}

	@Test
	fun `Assert article page title, content and status code`() {
		println(">> Assert article page title, content and status code")
		val title = "Lorem"
		val entity = restTemplate.getForEntity<String>("/article/${title.toSlug()}")
		assertThat(entity.statusCode).isEqualTo(HttpStatus.OK)
		assertThat(entity.body).contains(title, "Lorem", "dolor sit amet")
	}

	@AfterAll
	fun teardown() {
		println(">> Tear down")
	}

}
----

Start (or restart) the web application, and go to `http://localhost:8080/`, you should see the list of articles with clickable links to see a specific article.

== Expondo a API HTTP

We are now going to implement the HTTP API via `@RestController` annotated controllers.

`src/main/kotlin/com/example/blog/HttpControllers.kt`
[source,kotlin]
----
@RestController
@RequestMapping("/api/article")
class ArticleController(private val repository: ArticleRepository) {

	@GetMapping("/")
	fun findAll() = repository.findAllByOrderByAddedAtDesc()

	@GetMapping("/{slug}")
	fun findOne(@PathVariable slug: String) =
			repository.findBySlug(slug) ?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "This article does not exist")

}

@RestController
@RequestMapping("/api/user")
class UserController(private val repository: UserRepository) {

	@GetMapping("/")
	fun findAll() = repository.findAll()

	@GetMapping("/{login}")
	fun findOne(@PathVariable login: String) =
			repository.findByLogin(login) ?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "This user does not exist")
}
----

For tests, instead of integration tests, we are going to leverage `@WebMvcTest` and https://mockk.io/[Mockk] which is similar to https://site.mockito.org/[Mockito] but better suited for Kotlin.

Since `@MockBean` and `@SpyBean` annotations are specific to Mockito, we are going to leverage https://github.com/Ninja-Squad/springmockk[SpringMockK] which provides similar `@MockkBean` and `@SpykBean` annotations for Mockk.

With Gradle:

`build.gradle.kts`
[source,kotlin]
----
testImplementation("org.springframework.boot:spring-boot-starter-test") {
	exclude(module = "mockito-core")
}
testImplementation("org.junit.jupiter:junit-jupiter-api")
testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
testImplementation("com.ninja-squad:springmockk:4.0.0")
----

Or with Maven:

`pom.xml`
[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-engine</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>com.ninja-squad</groupId>
	<artifactId>springmockk</artifactId>
	<version>4.0.0</version>
	<scope>test</scope>
</dependency>
----

`src/test/kotlin/com/example/blog/HttpControllersTests.kt`
[source,kotlin]
----
@WebMvcTest
class HttpControllersTests(@Autowired val mockMvc: MockMvc) {

	@MockkBean
	lateinit var userRepository: UserRepository

	@MockkBean
	lateinit var articleRepository: ArticleRepository

	@Test
	fun `List articles`() {
		val johnDoe = User("johnDoe", "John", "Doe")
		val lorem5Article = Article("Lorem", "Lorem", "dolor sit amet", johnDoe)
		val ipsumArticle = Article("Ipsum", "Ipsum", "dolor sit amet", johnDoe)
		every { articleRepository.findAllByOrderByAddedAtDesc() } returns listOf(lorem5Article, ipsumArticle)
		mockMvc.perform(get("/api/article/").accept(MediaType.APPLICATION_JSON))
				.andExpect(status().isOk)
				.andExpect(content().contentType(MediaType.APPLICATION_JSON))
				.andExpect(jsonPath("\$.[0].author.login").value(johnDoe.login))
				.andExpect(jsonPath("\$.[0].slug").value(lorem5Article.slug))
				.andExpect(jsonPath("\$.[1].author.login").value(johnDoe.login))
				.andExpect(jsonPath("\$.[1].slug").value(ipsumArticle.slug))
	}

	@Test
	fun `List users`() {
		val johnDoe = User("johnDoe", "John", "Doe")
		val janeDoe = User("janeDoe", "Jane", "Doe")
		every { userRepository.findAll() } returns listOf(johnDoe, janeDoe)
		mockMvc.perform(get("/api/user/").accept(MediaType.APPLICATION_JSON))
				.andExpect(status().isOk)
				.andExpect(content().contentType(MediaType.APPLICATION_JSON))
				.andExpect(jsonPath("\$.[0].login").value(johnDoe.login))
				.andExpect(jsonPath("\$.[1].login").value(janeDoe.login))
	}
}
----

NOTE: `$` needs to be escaped in strings as it is used for string interpolation.

== Propriedades de configuração

In Kotlin, the recommended way to manage your application properties is to use read-only properties.

`src/main/kotlin/com/example/blog/BlogProperties.kt`
[source,kotlin]
----
@ConfigurationProperties("blog")
data class BlogProperties(var title: String, val banner: Banner) {
	data class Banner(val title: String? = null, val content: String)
}
----

Then we enable it at `BlogApplication` level.

`src/main/kotlin/com/example/blog/BlogApplication.kt`
[source,kotlin]
----
@SpringBootApplication
@EnableConfigurationProperties(BlogProperties::class)
class BlogApplication {
	// ...
}
----

To generate https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor[your own metadata] in order to get these custom properties recognized by your IDE, https://kotlinlang.org/docs/reference/kapt.html[kapt should be configured] with the `spring-boot-configuration-processor` dependency as following.

`build.gradle.kts`
[source,kotlin]
----
plugins {
	...
	kotlin("kapt") version "1.8.0"
}

dependencies {
	...
	kapt("org.springframework.boot:spring-boot-configuration-processor")
}
----

NOTE: Note that some features (such as detecting the default value or deprecated items) are not working due to limitations in the model kapt provides. Also annotation processing is not yet supported with Maven due to https://youtrack.jetbrains.com/issue/KT-18022[KT-18022], see https://github.com/spring-io/initializr/issues/438[initializr#438] for more details.

In IntelliJ IDEA:

 - Make sure Spring Boot plugin in enabled in menu File | Settings | Plugins | Spring Boot
 - Enable annotation processing via menu File | Settings | Build, Execution, Deployment | Compiler | Annotation Processors | Enable annotation processing
 - Since https://youtrack.jetbrains.com/issue/KT-15040[Kapt is not yet integrated in IDEA], you need to run manually the command `./gradlew kaptKotlin` to generate the metadata

Your custom properties should now be recognized when editing `application.properties` (autocomplete, validation, etc.).

`src/main/resources/application.properties`
[source,properties]
----
blog.title=Blog
blog.banner.title=Warning
blog.banner.content=The blog will be down tomorrow.
----

Edit the template and the controller accordingly.

`src/main/resources/templates/blog.mustache`
[source]
----
{{> header}}

<div class="articles">

	{{#banner.title}}
	<section>
		<header class="banner">
			<h2 class="banner-title">{{banner.title}}</h2>
		</header>
		<div class="banner-content">
			{{banner.content}}
		</div>
	</section>
	{{/banner.title}}

	...

</div>

{{> footer}}
----

`src/main/kotlin/com/example/blog/HtmlController.kt`
[source,kotlin]
----
@Controller
class HtmlController(private val repository: ArticleRepository,
					 private val properties: BlogProperties) {

	@GetMapping("/")
	fun blog(model: Model): String {
		model["title"] = properties.title
		model["banner"] = properties.banner
		model["articles"] = repository.findAllByOrderByAddedAtDesc().map { it.render() }
		return "blog"
	}

	// ...
----

Restart the web application, refresh `http://localhost:8080/`, you should see the banner on the blog homepage.

== Conclusão

We have now finished to build this sample Kotlin blog application. The source code https://github.com/spring-guides/tut-spring-boot-kotlin[is available on Github]. You can also have a look to https://docs.spring.io/spring/docs/current/spring-framework-reference/languages.html#kotlin[Spring Framework] and https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-kotlin.html[Spring Boot] reference documentation if you need more details on specific features.
